//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommNavigationObjects/CommGridMap.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once

#include "CommBasicObjects/CommTimeStampOpcUa.hh"

namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommNavigationObjectsIDL::CommGridMap
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjectsIDL::CommGridMap *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add id
	ret->add(
		SelfDescription(&(obj->id), "Id")
	);
	// add is_valid
	ret->add(
		SelfDescription(&(obj->is_valid), "Is_valid")
	);
	// add time
	ret->add(
		SelfDescription(&(obj->time), "Time")
	);
	// add xOffsetMM
	ret->add(
		SelfDescription(&(obj->xOffsetMM), "XOffsetMM")
	);
	// add yOffsetMM
	ret->add(
		SelfDescription(&(obj->yOffsetMM), "YOffsetMM")
	);
	// add xOffsetCells
	ret->add(
		SelfDescription(&(obj->xOffsetCells), "XOffsetCells")
	);
	// add yOffsetCells
	ret->add(
		SelfDescription(&(obj->yOffsetCells), "YOffsetCells")
	);
	// add cellSizeMM
	ret->add(
		SelfDescription(&(obj->cellSizeMM), "CellSizeMM")
	);
	// add xSizeMM
	ret->add(
		SelfDescription(&(obj->xSizeMM), "XSizeMM")
	);
	// add ySizeMM
	ret->add(
		SelfDescription(&(obj->ySizeMM), "YSizeMM")
	);
	// add xSizeCells
	ret->add(
		SelfDescription(&(obj->xSizeCells), "XSizeCells")
	);
	// add ySizeCells
	ret->add(
		SelfDescription(&(obj->ySizeCells), "YSizeCells")
	);
	// add size
	ret->add(
		SelfDescription(&(obj->size), "Size")
	);
	// add cell
	ret->add(
		SelfDescription(&(obj->cell), "Cell")
	);
	return ret;
} // end SelfDescription


// serialization for CommGridMap
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjects::CommGridMap *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
