//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommBasicObjects/CommBasePositionUpdate.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once

#include "CommBasicObjects/CommTimeStampOpcUa.hh"
#include "CommBasicObjects/CommBasePoseOpcUa.hh"
#include "CommBasicObjects/CommBasePoseOpcUa.hh"
#include "CommBasicObjects/CommBaseVelocityOpcUa.hh"
#include "CommBasicObjects/CommBaseVelocityOpcUa.hh"

namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommBasicObjectsIDL::CommBasePositionUpdate
template <>
inline IDescription::shp_t SelfDescription(CommBasicObjectsIDL::CommBasePositionUpdate *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add timeStamp
	ret->add(
		SelfDescription(&(obj->timeStamp), "TimeStamp")
	);
	// add pose
	ret->add(
		SelfDescription(&(obj->pose), "Pose")
	);
	// add correctedPose
	ret->add(
		SelfDescription(&(obj->correctedPose), "CorrectedPose")
	);
	// add velocity
	ret->add(
		SelfDescription(&(obj->velocity), "Velocity")
	);
	// add correctedVelocity
	ret->add(
		SelfDescription(&(obj->correctedVelocity), "CorrectedVelocity")
	);
	return ret;
} // end SelfDescription


// serialization for CommBasePositionUpdate
template <>
inline IDescription::shp_t SelfDescription(CommBasicObjects::CommBasePositionUpdate *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
