//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommBasicObjects/CommMobileLaserScan.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once

#include "CommBasicObjects/CommBaseStateOpcUa.hh"
#include "CommBasicObjects/LaserScan6DPoseOpcUa.hh"
#include "CommBasicObjects/CommPose3dOpcUa.hh"

namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommBasicObjectsIDL::CommMobileLaserScan
template <>
inline IDescription::shp_t SelfDescription(CommBasicObjectsIDL::CommMobileLaserScan *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add base_state
	ret->add(
		SelfDescription(&(obj->base_state), "Base_state")
	);
	// add laser_scan_pose
	ret->add(
		SelfDescription(&(obj->laser_scan_pose), "Laser_scan_pose")
	);
	// add laser_world_pose
	ret->add(
		SelfDescription(&(obj->laser_world_pose), "Laser_world_pose")
	);
	return ret;
} // end SelfDescription


// serialization for CommMobileLaserScan
template <>
inline IDescription::shp_t SelfDescription(CommBasicObjects::CommMobileLaserScan *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
