//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommNavigationObjects/CommPlannerGoal.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once


namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommNavigationObjectsIDL::CommPlannerGoal
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjectsIDL::CommPlannerGoal *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add id
	ret->add(
		SelfDescription(&(obj->id), "Id")
	);
	// add flag
	ret->add(
		SelfDescription(&(obj->flag), "Flag")
	);
	// add xWayPoint
	ret->add(
		SelfDescription(&(obj->xWayPoint), "XWayPoint")
	);
	// add yWayPoint
	ret->add(
		SelfDescription(&(obj->yWayPoint), "YWayPoint")
	);
	// add hWayPoint
	ret->add(
		SelfDescription(&(obj->hWayPoint), "HWayPoint")
	);
	// add xGoalPoint
	ret->add(
		SelfDescription(&(obj->xGoalPoint), "XGoalPoint")
	);
	// add yGoalPoint
	ret->add(
		SelfDescription(&(obj->yGoalPoint), "YGoalPoint")
	);
	// add hGoalPoint
	ret->add(
		SelfDescription(&(obj->hGoalPoint), "HGoalPoint")
	);
	return ret;
} // end SelfDescription


// serialization for CommPlannerGoal
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjects::CommPlannerGoal *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
