//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SmartMapperGridMapSeRoNetSDKPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "CommNavigationObjects/CommGridMapOpcUa.hh"
#include "CommNavigationObjects/CommGridMapRequestOpcUa.hh"
#include "CommBasicObjects/CommMobileLaserScanOpcUa.hh"

// create a static instance of the SeRoNetSDKPortFactory
static SmartMapperGridMapSeRoNetSDKPortFactory SeRoNetSDKPortFactory;

SmartMapperGridMapSeRoNetSDKPortFactory::SmartMapperGridMapSeRoNetSDKPortFactory()
{  
	componentImpl = 0;
	SmartMapperGridMap::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

SmartMapperGridMapSeRoNetSDKPortFactory::~SmartMapperGridMapSeRoNetSDKPortFactory()
{  }

void SmartMapperGridMapSeRoNetSDKPortFactory::initialize(SmartMapperGridMap *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int SmartMapperGridMapSeRoNetSDKPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&SmartMapperGridMapSeRoNetSDKPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}

Smart::IPushClientPattern<CommBasicObjects::CommMobileLaserScan> * SmartMapperGridMapSeRoNetSDKPortFactory::createLaserServiceIn()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommMobileLaserScan>(componentImpl);
}


Smart::IPushServerPattern<CommNavigationObjects::CommGridMap> * SmartMapperGridMapSeRoNetSDKPortFactory::createCurrMapOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<CommNavigationObjects::CommGridMap>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap,SmartACE::QueryId> * SmartMapperGridMapSeRoNetSDKPortFactory::createLtmQueryServer(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::QueryServer<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap,SmartACE::QueryId> * SmartMapperGridMapSeRoNetSDKPortFactory::createCurrQueryServer(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::QueryServer<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap>(componentImpl, serviceName);
}


int SmartMapperGridMapSeRoNetSDKPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int SmartMapperGridMapSeRoNetSDKPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void SmartMapperGridMapSeRoNetSDKPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
