//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommRobotinoObjects/CommPathNavigationGoal.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once

#include "CommRobotinoObjects/CommNavigationPathsOpcUa.hh"

namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommRobotinoObjectsIDL::CommPathNavigationGoal
template <>
inline IDescription::shp_t SelfDescription(CommRobotinoObjectsIDL::CommPathNavigationGoal *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add goalID
	ret->add(
		SelfDescription(&(obj->goalID), "GoalID")
	);
	// add paths
	ret->add(
		SelfDescription(&(obj->paths), "Paths")
	);
	// add goalX
	ret->add(
		SelfDescription(&(obj->goalX), "GoalX")
	);
	// add goalY
	ret->add(
		SelfDescription(&(obj->goalY), "GoalY")
	);
	// add goal_id
	ret->add(
		SelfDescription(&(obj->goal_id), "Goal_id")
	);
	// add startX
	ret->add(
		SelfDescription(&(obj->startX), "StartX")
	);
	// add startY
	ret->add(
		SelfDescription(&(obj->startY), "StartY")
	);
	// add start_id
	ret->add(
		SelfDescription(&(obj->start_id), "Start_id")
	);
	return ret;
} // end SelfDescription


// serialization for CommPathNavigationGoal
template <>
inline IDescription::shp_t SelfDescription(CommRobotinoObjects::CommPathNavigationGoal *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
