//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommNavigationObjects/CommGridMapRequest.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once


namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommNavigationObjectsIDL::CommGridMapRequest
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjectsIDL::CommGridMapRequest *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add id
	ret->add(
		SelfDescription(&(obj->id), "Id")
	);
	// add xOffsetMM
	ret->add(
		SelfDescription(&(obj->xOffsetMM), "XOffsetMM")
	);
	// add yOffsetMM
	ret->add(
		SelfDescription(&(obj->yOffsetMM), "YOffsetMM")
	);
	// add xSizeMM
	ret->add(
		SelfDescription(&(obj->xSizeMM), "XSizeMM")
	);
	// add ySizeMM
	ret->add(
		SelfDescription(&(obj->ySizeMM), "YSizeMM")
	);
	// add curLtmState
	ret->add(
		SelfDescription(&(obj->curLtmState), "CurLtmState")
	);
	// add curLtmThreshold
	ret->add(
		SelfDescription(&(obj->curLtmThreshold), "CurLtmThreshold")
	);
	return ret;
} // end SelfDescription


// serialization for CommGridMapRequest
template <>
inline IDescription::shp_t SelfDescription(CommNavigationObjects::CommGridMapRequest *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
