//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommTrackingObjects/CommTrackingGoal.hh"

#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ComplexType.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNetSDK/SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once


namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
	
// serialization for CommTrackingObjectsIDL::CommTrackingGoal
template <>
inline IDescription::shp_t SelfDescription(CommTrackingObjectsIDL::CommTrackingGoal *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	// add trackingType
	ret->add(
		SelfDescription(&(obj->trackingType), "TrackingType")
	);
	// add angle
	ret->add(
		SelfDescription(&(obj->angle), "Angle")
	);
	// add distance
	ret->add(
		SelfDescription(&(obj->distance), "Distance")
	);
	// add x
	ret->add(
		SelfDescription(&(obj->x), "X")
	);
	// add y
	ret->add(
		SelfDescription(&(obj->y), "Y")
	);
	// add isValid
	ret->add(
		SelfDescription(&(obj->isValid), "IsValid")
	);
	// add cov
	ret->add(
		SelfDescription(&(obj->cov), "Cov")
	);
	return ret;
} // end SelfDescription


// serialization for CommTrackingGoal
template <>
inline IDescription::shp_t SelfDescription(CommTrackingObjects::CommTrackingGoal *obj, std::string name)
{
	return SelfDescription(&(obj->set()),name); 
} // end SelfDescription


} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
