//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "CommNavigationObjects/CommGridMapOpcUa.hh"
#include "CommBasicObjects/CommBaseStateOpcUa.hh"
#include "CommNavigationObjects/CommPlannerGoalOpcUa.hh"
#include "CommNavigationObjects/CommPlannerEventParameterOpcUa.hh"
#include "CommNavigationObjects/PlannerEventStateOpcUa.hh"
#include "CommNavigationObjects/CommPlannerEventResultOpcUa.hh"

// create a static instance of the SeRoNetSDKPortFactory
static SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory SeRoNetSDKPortFactory;

SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory()
{  
	componentImpl = 0;
	SmartPlannerBreadthFirstSearch::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::~SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory()
{  }

void SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::initialize(SmartPlannerBreadthFirstSearch *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}

Smart::IPushClientPattern<CommNavigationObjects::CommGridMap> * SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::createCurMapClient()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommNavigationObjects::CommGridMap>(componentImpl);
}

Smart::IPushClientPattern<CommBasicObjects::CommBaseState> * SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::createBaseStateClient()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommBaseState>(componentImpl);
}


Smart::IPushServerPattern<CommNavigationObjects::CommPlannerGoal> * SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::createPlannerGoalServer(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<CommNavigationObjects::CommPlannerGoal>(componentImpl, serviceName);
}

Smart::IEventServerPattern<CommNavigationObjects::CommPlannerEventParameter, CommNavigationObjects::CommPlannerEventResult, CommNavigationObjects::PlannerEventState,SmartACE::EventId> * SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::createPlannerEventServer(const std::string &serviceName, Smart::IEventTestHandler<CommNavigationObjects::CommPlannerEventParameter, CommNavigationObjects::CommPlannerEventResult, CommNavigationObjects::PlannerEventState> *plannerEventServerEventTestHandler)
{
	return new SeRoNet::OPCUA::Server::EventServer<CommNavigationObjects::CommPlannerEventParameter, CommNavigationObjects::CommPlannerEventResult, CommNavigationObjects::PlannerEventState>(componentImpl, serviceName, plannerEventServerEventTestHandler);
}


int SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void SmartPlannerBreadthFirstSearchSeRoNetSDKPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
